
services:
  base_img:
    build:
      context: ./base_img
      dockerfile: base_img.Dockerfile
    image: base_img

  sk-boost-1:
    container_name: sk-boost-c-1
    build:
      context: ./../socket_boost
      dockerfile: socket-boost.Dockerfile
    depends_on:
      - base_img
    privileged: true
    network_mode: host
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
      - /lib/modules:/lib/modules:ro
      - ./../socket_boost:/socket_boost
    environment:
      - NETDEV=eth0
      - REMOTE_IP=192.168.88.130
  

  sk-boost-2:
    container_name: sk-boost-c-2
    build:
      context: ./../socket_boost
      dockerfile: socket-boost.Dockerfile
    depends_on:
      - base_img
    privileged: true
    network_mode: host
    volumes:
      - /sys/kernel/debug:/sys/kernel/debug
      - /lib/modules:/lib/modules:ro 
      - ./../socket_boost:/socket_boost
    environment:
      - NETDEV=eth0
      - REMOTE_IP=192.168.88.130

networks:
  sk-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
